# Project: main_project
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main_project.o storage_project.o
LINKOBJ  = main_project.o storage_project.o
LIBS     = -L"C:/Users/SAMSUNG/Desktop/Dev-Cpp/MinGW64/lib32" -L"C:/Users/SAMSUNG/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -static-libgcc -m32 -g3
INCS     = -I"C:/Users/SAMSUNG/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/SAMSUNG/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/SAMSUNG/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/SAMSUNG/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/SAMSUNG/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/SAMSUNG/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/SAMSUNG/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = main_project.exe
CXXFLAGS = $(CXXINCS) -m32 -g3
CFLAGS   = $(INCS) -m32 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main_project.o: main_project.c
	$(CC) -c main_project.c -o main_project.o $(CFLAGS)

storage_project.o: storage_project.c
	$(CC) -c storage_project.c -o storage_project.o $(CFLAGS)
